baseURL = "https://sampta2023.github.io/"
languageCode = "en-us"
theme = "hyde"
title = "SAMPTA 2023"
[params]
	description = "Sampling Theory and Applications Conference. July 10-14 at Yale."
	disqusShortname = ""
	googleAnalytics = ""
	layoutReverse = false
	theme = "hyde"
	themeColor = "theme-base-08"
[params.meta]
	keywords = "complex analysis, sampling theory"

[Menus]
  main = [
      {Name = "Submit your paper", URL = "https://openreview.net/group?id=SampTA/2023/Conference"}
  ]
