baseURL = "https://sampta2023.github.io/"
languageCode = "en-us"
theme = "hyde"
title = "SAMPTA 2023"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
[params.meta]
description = "Sampling Theory and Applications Conference"
keywords = "complex analysis, sampling theory"